# Generated by Django 5.2.17 on 2026-09-07 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('pipeline', '0002_remove_historicalwindow_pipe_window_published_hashes_and_more'),
        ('registry', '0003_remove_company_reg_company_cnpj_basic_8d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CNEFE', 'CNEFE'), ('MUNICIPAL_BOUNDARIES', 'Malha municipal')], max_length=32)),
                ('version', models.CharField(max_length=40)),
                ('content_hash', models.CharField(max_length=64)),
                ('manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fonte geográfica',
                'verbose_name_plural': 'fontes geográficas',
                'db_table': 'cartography_geographic_source',
                'ordering': ('kind', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'version', 'content_hash'), name='cart_source_kind_ver_hash_uniq'), models.CheckConstraint(condition=models.Q(('content_hash__regex', '^[0-9a-f]{64}$')), name='cart_source_hash_sha256')],
            },
        ),
        migrations.CreateModel(
            name='CartographicProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registry_manifest_hash', models.CharField(max_length=64)),
                ('algorithm_version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('PREPARING', 'Em preparação'), ('PUBLISHED', 'Publicada'), ('SUPERSEDED', 'Substituída'), ('FAILED_QUALITY_GATE', 'Reprovada na qualidade'), ('FAILED', 'Falhou')], default='PREPARING', max_length=32)),
                ('quality_report', models.JSONField(default=dict)),
                ('eligible_count', models.PositiveBigIntegerField(default=0)),
                ('located_count', models.PositiveBigIntegerField(default=0)),
                ('address_count', models.PositiveBigIntegerField(default=0)),
                ('postal_code_count', models.PositiveBigIntegerField(default=0)),
                ('unlocated_count', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('historical_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartographic_projections', to='pipeline.historicalwindow')),
                ('boundary_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boundary_projections', to='cartography.geographicsource')),
                ('cnefe_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cnefe_projections', to='cartography.geographicsource')),
            ],
            options={
                'verbose_name': 'projeção cartográfica',
                'verbose_name_plural': 'projeções cartográficas',
                'db_table': 'cartography_projection',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AddressResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_version', models.CharField(default='1.0.0', max_length=20)),
                ('fingerprint', models.CharField(max_length=64)),
                ('postal_code', models.CharField(blank=True, max_length=8)),
                ('normalized_street', models.CharField(blank=True, max_length=300)),
                ('normalized_number', models.CharField(blank=True, max_length=40)),
                ('method', models.CharField(choices=[('ADDRESS', 'Endereço CNEFE'), ('POSTAL_CODE', 'Aproximação por CEP'), ('UNLOCATED', 'Não localizado')], max_length=16)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('cnefe_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cnefe_address_code', models.CharField(blank=True, max_length=40)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('dispersion_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_resolutions', to='geography.municipality')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_resolutions', to='cartography.geographicsource')),
            ],
            options={
                'verbose_name': 'resolução de endereço',
                'verbose_name_plural': 'resoluções de endereço',
                'db_table': 'cartography_address_resolution',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField()),
                ('bbox', models.JSONField(default=list)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartographic_boundaries', to='geography.municipality')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipality_boundaries', to='cartography.geographicsource')),
            ],
            options={
                'verbose_name': 'limite municipal',
                'verbose_name_plural': 'limites municipais',
                'db_table': 'cartography_municipality_boundary',
                'ordering': ('municipality__name',),
            },
        ),
        migrations.CreateModel(
            name='CartographicObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('location_method', models.CharField(choices=[('ADDRESS', 'Endereço CNEFE'), ('POSTAL_CODE', 'Aproximação por CEP'), ('UNLOCATED', 'Não localizado')], max_length=16)),
                ('cnefe_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=8)),
                ('main_cnae_code', models.CharField(blank=True, max_length=7)),
                ('branch_type', models.CharField(max_length=2)),
                ('company_size_code', models.CharField(blank=True, max_length=2)),
                ('tax_profile', models.CharField(choices=[('MEI', 'MEI'), ('SIMPLES', 'Simples Nacional'), ('REGULAR', 'Não optante'), ('UNKNOWN', 'Não informado')], max_length=12)),
                ('address_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='cartography.addressresolution')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartographic_observations', to='registry.company')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartographic_observations', to='registry.establishment')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartographic_observations', to='geography.municipality')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartographic_observations', to='pipeline.competencerevision')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='cartography.cartographicprojection')),
            ],
            options={
                'verbose_name': 'observação cartográfica',
                'verbose_name_plural': 'observações cartográficas',
                'db_table': 'cartography_observation',
                'indexes': [models.Index(fields=['projection', 'revision', 'municipality'], name='cart_obs_proj_rev_city'), models.Index(fields=['projection', 'revision', 'main_cnae_code'], name='cart_obs_proj_rev_cnae'), models.Index(fields=['projection', 'revision', 'latitude', 'longitude'], name='cart_obs_proj_rev_coord'), models.Index(fields=['projection', 'revision', 'branch_type'], name='cart_obs_proj_rev_branch'), models.Index(fields=['projection', 'revision', 'company_size_code'], name='cart_obs_proj_rev_size'), models.Index(fields=['projection', 'revision', 'tax_profile'], name='cart_obs_proj_rev_tax'), models.Index(fields=['projection', 'revision', 'location_method'], name='cart_obs_proj_rev_method')],
                'constraints': [models.UniqueConstraint(fields=('projection', 'revision', 'establishment'), name='cart_observation_projection_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='cart_observation_coord_pair'), models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='cart_observation_lat_range'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='cart_observation_lng_range'), models.CheckConstraint(condition=models.Q(('cnefe_level__isnull', True), models.Q(('cnefe_level__gte', 1), ('cnefe_level__lte', 6)), _connector='OR'), name='cart_observation_level_range')],
            },
        ),
        migrations.AddConstraint(
            model_name='cartographicprojection',
            constraint=models.UniqueConstraint(fields=('historical_window', 'cnefe_source', 'boundary_source', 'registry_manifest_hash', 'algorithm_version'), name='cart_projection_inputs_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cartographicprojection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('historical_window',), name='cart_one_published_projection'),
        ),
        migrations.AddConstraint(
            model_name='cartographicprojection',
            constraint=models.CheckConstraint(condition=models.Q(('registry_manifest_hash__regex', '^[0-9a-f]{64}$')), name='cart_projection_registry_sha256'),
        ),
        migrations.AddConstraint(
            model_name='cartographicprojection',
            constraint=models.CheckConstraint(condition=models.Q(('located_count__lte', models.F('eligible_count'))), name='cart_projection_located_lte_all'),
        ),
        migrations.AddIndex(
            model_name='addressresolution',
            index=models.Index(fields=['source', 'algorithm_version', 'municipality', 'postal_code'], name='cart_res_src_city_cep'),
        ),
        migrations.AddIndex(
            model_name='addressresolution',
            index=models.Index(fields=['source', 'method'], name='cart_res_source_method'),
        ),
        migrations.AddConstraint(
            model_name='addressresolution',
            constraint=models.UniqueConstraint(fields=('source', 'municipality', 'algorithm_version', 'fingerprint'), name='cart_resolution_source_city_fp_uniq'),
        ),
        migrations.AddConstraint(
            model_name='addressresolution',
            constraint=models.CheckConstraint(condition=models.Q(('fingerprint__regex', '^[0-9a-f]{64}$')), name='cart_resolution_fp_sha256'),
        ),
        migrations.AddConstraint(
            model_name='addressresolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='cart_resolution_coord_pair'),
        ),
        migrations.AddConstraint(
            model_name='addressresolution',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='cart_resolution_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='addressresolution',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='cart_resolution_lng_range'),
        ),
        migrations.AddConstraint(
            model_name='addressresolution',
            constraint=models.CheckConstraint(condition=models.Q(('cnefe_level__isnull', True), models.Q(('cnefe_level__gte', 1), ('cnefe_level__lte', 6)), _connector='OR'), name='cart_resolution_level_range'),
        ),
        migrations.AddConstraint(
            model_name='municipalityboundary',
            constraint=models.UniqueConstraint(fields=('source', 'municipality'), name='cart_boundary_source_city_uniq'),
        ),
        migrations.AddConstraint(
            model_name='municipalityboundary',
            constraint=models.CheckConstraint(condition=models.Q(('center_latitude__gte', -90), ('center_latitude__lte', 90)), name='cart_boundary_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='municipalityboundary',
            constraint=models.CheckConstraint(condition=models.Q(('center_longitude__gte', -180), ('center_longitude__lte', 180)), name='cart_boundary_lng_range'),
        ),
    ]
