# Generated by Django 5.2.17 on 2026-09-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartographicobservation',
            name='address_resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='cartography.addressresolution'),
        ),
    ]
