# Generated by Django 5.2.17 on 2026-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0002_alter_cartographicobservation_address_resolution'),
        ('geography', '0001_initial'),
        ('pipeline', '0002_remove_historicalwindow_pipe_window_published_hashes_and_more'),
        ('registry', '0003_remove_company_reg_company_cnpj_basic_8d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnaeSubclass',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('source', models.CharField(default='IBGE CNAE API v2', max_length=120)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subclasse CNAE',
                'verbose_name_plural': 'subclasses CNAE',
                'db_table': 'cartography_cnae_subclass',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='cartographicobservation',
            name='activity_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE cartography_observation AS observation
                SET activity_start_date = snapshot.activity_start_date
                FROM registry_establishment_snapshot AS snapshot
                WHERE snapshot.revision_id = observation.revision_id
                  AND snapshot.establishment_id = observation.establishment_id
                  AND observation.activity_start_date IS DISTINCT FROM snapshot.activity_start_date
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name='cartographicobservation',
            index=models.Index(fields=['projection', 'revision', 'activity_start_date'], name='cart_obs_proj_rev_start'),
        ),
        migrations.AddConstraint(
            model_name='cnaesubclass',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[0-9]{7}$')), name='cart_cnae_subclass_code_7d'),
        ),
    ]
