# Generated by Django 5.2.17 on 2026-09-07 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartography", "0003_cnaesubclass_and_more"),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicsource",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CNEFE", "CNEFE"),
                    ("MUNICIPAL_BOUNDARIES", "Malha municipal"),
                    ("MUNICIPAL_POPULATION", "População municipal"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MunicipalityPopulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_year", models.PositiveSmallIntegerField()),
                ("population", models.PositiveBigIntegerField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="population_references",
                        to="geography.municipality",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipality_populations",
                        to="cartography.geographicsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "população municipal",
                "verbose_name_plural": "populações municipais",
                "db_table": "cartography_municipality_population",
                "ordering": ("-reference_year", "municipality__name"),
            },
        ),
        migrations.AddConstraint(
            model_name="municipalitypopulation",
            constraint=models.UniqueConstraint(
                fields=("municipality", "reference_year"),
                name="cart_population_city_year_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="municipalitypopulation",
            constraint=models.CheckConstraint(
                condition=models.Q(("population__gt", 0)),
                name="cart_population_positive",
            ),
        ),
    ]
