# Generated by Django 5.2.17 on 2026-08-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_basic', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'registry_company',
                'constraints': [models.CheckConstraint(condition=models.Q(('cnpj_basic__regex', '^[0-9]{8}$')), name='reg_company_cnpj_basic_8d')],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='registry.company')),
            ],
            options={
                'verbose_name': 'estabelecimento',
                'verbose_name_plural': 'estabelecimentos',
                'db_table': 'registry_establishment',
            },
        ),
        migrations.CreateModel(
            name='EstablishmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_type', models.CharField(max_length=2)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('trade_name_search', models.CharField(blank=True, db_index=True, max_length=255)),
                ('registration_status_code', models.CharField(max_length=2)),
                ('registration_status_date', models.DateField(blank=True, null=True)),
                ('registration_status_reason_code', models.CharField(blank=True, max_length=2, null=True)),
                ('activity_start_date', models.DateField(blank=True, null=True)),
                ('main_cnae_code', models.CharField(blank=True, max_length=7, null=True)),
                ('street_type', models.CharField(blank=True, max_length=40)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('street_number', models.CharField(blank=True, max_length=20)),
                ('address_complement', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=8)),
                ('state_code', models.CharField(max_length=2)),
                ('municipality_tom_code', models.CharField(max_length=4)),
                ('is_in_region', models.BooleanField()),
                ('record_hash', models.CharField(max_length=64)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='registry.establishment')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishment_snapshots', to='geography.municipality')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishment_snapshots', to='pipeline.competencerevision')),
            ],
            options={
                'verbose_name': 'fotografia de estabelecimento',
                'verbose_name_plural': 'fotografias de estabelecimento',
                'db_table': 'registry_establishment_snapshot',
            },
        ),
        migrations.CreateModel(
            name='PartnerParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_key', models.CharField(max_length=64)),
                ('partner_type', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica'), ('FOREIGN', 'Estrangeiro')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_participations', to='registry.company')),
            ],
            options={
                'verbose_name': 'participação societária',
                'verbose_name_plural': 'participações societárias',
                'db_table': 'registry_partner_participation',
            },
        ),
        migrations.CreateModel(
            name='PartnerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('partner_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('qualification_code', models.CharField(blank=True, max_length=2, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('record_hash', models.CharField(max_length=64)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='registry.partnerparticipation')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_snapshots', to='pipeline.competencerevision')),
            ],
            options={
                'verbose_name': 'fotografia de participação societária',
                'verbose_name_plural': 'fotografias de participação societária',
                'db_table': 'registry_partner_snapshot',
            },
        ),
        migrations.CreateModel(
            name='CompanySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('legal_name_search', models.CharField(db_index=True, max_length=255)),
                ('legal_nature_code', models.CharField(blank=True, max_length=4, null=True)),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('company_size_code', models.CharField(blank=True, max_length=2, null=True)),
                ('simples_optant', models.BooleanField(blank=True, null=True)),
                ('simples_option_date', models.DateField(blank=True, null=True)),
                ('simples_exclusion_date', models.DateField(blank=True, null=True)),
                ('mei_optant', models.BooleanField(blank=True, null=True)),
                ('mei_option_date', models.DateField(blank=True, null=True)),
                ('mei_exclusion_date', models.DateField(blank=True, null=True)),
                ('record_hash', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='registry.company')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_snapshots', to='pipeline.competencerevision')),
            ],
            options={
                'verbose_name': 'fotografia de empresa',
                'verbose_name_plural': 'fotografias de empresa',
                'db_table': 'registry_company_snapshot',
                'constraints': [models.UniqueConstraint(fields=('revision', 'company'), name='reg_company_snapshot_uniq'), models.CheckConstraint(condition=models.Q(('share_capital__isnull', True), ('share_capital__gte', 0), _connector='OR'), name='reg_company_capital_nonnegative'), models.CheckConstraint(condition=models.Q(('record_hash__regex', '^[0-9a-f]{64}$')), name='reg_company_snapshot_hash_sha256')],
            },
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.CheckConstraint(condition=models.Q(('cnpj__regex', '^[0-9]{14}$')), name='reg_establishment_cnpj_14d'),
        ),
        migrations.AddIndex(
            model_name='establishmentsnapshot',
            index=models.Index(fields=['revision', 'municipality', 'is_in_region'], name='reg_est_rev_city_region'),
        ),
        migrations.AddIndex(
            model_name='establishmentsnapshot',
            index=models.Index(fields=['revision', 'main_cnae_code', 'is_in_region'], name='reg_est_rev_cnae_region'),
        ),
        migrations.AddConstraint(
            model_name='establishmentsnapshot',
            constraint=models.UniqueConstraint(fields=('revision', 'establishment'), name='reg_establishment_snapshot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='establishmentsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('municipality_tom_code__regex', '^[0-9]{4}$')), name='reg_est_snapshot_tom_4d'),
        ),
        migrations.AddConstraint(
            model_name='establishmentsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('state_code__regex', '^[A-Z]{2}$')), name='reg_est_snapshot_uf_2letters'),
        ),
        migrations.AddConstraint(
            model_name='establishmentsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('postal_code', ''), ('postal_code__regex', '^[0-9]{8}$'), _connector='OR'), name='reg_est_snapshot_postal_8d'),
        ),
        migrations.AddConstraint(
            model_name='establishmentsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('main_cnae_code__isnull', True), ('main_cnae_code', ''), ('main_cnae_code__regex', '^[0-9]{7}$'), _connector='OR'), name='reg_est_snapshot_cnae_7d'),
        ),
        migrations.AddConstraint(
            model_name='establishmentsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('record_hash__regex', '^[0-9a-f]{64}$')), name='reg_est_snapshot_hash_sha256'),
        ),
        migrations.AddConstraint(
            model_name='partnerparticipation',
            constraint=models.UniqueConstraint(fields=('company', 'partner_key'), name='reg_company_partner_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='partnersnapshot',
            constraint=models.UniqueConstraint(fields=('revision', 'participation'), name='reg_partner_snapshot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='partnersnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('partner_cnpj__isnull', True), ('partner_cnpj', ''), ('partner_cnpj__regex', '^[0-9]{14}$'), _connector='OR'), name='reg_partner_snapshot_cnpj_14d'),
        ),
        migrations.AddConstraint(
            model_name='partnersnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('record_hash__regex', '^[0-9a-f]{64}$')), name='reg_partner_snapshot_hash_sha256'),
        ),
    ]
