# Generated by Django 5.2.17 on 2026-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_remove_historicalwindow_pipe_window_published_hashes_and_more'),
        ('registry', '0002_partner_cnpj_basic'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='reg_company_cnpj_basic_8d',
        ),
        migrations.RemoveConstraint(
            model_name='establishment',
            name='reg_establishment_cnpj_14d',
        ),
        migrations.RemoveConstraint(
            model_name='partnersnapshot',
            name='reg_partner_snapshot_cnpj_basic_8d',
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('cnpj_basic__regex', '^[A-Z0-9]{8}$')), name='reg_company_cnpj_basic_8c'),
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.CheckConstraint(condition=models.Q(('cnpj__regex', '^[A-Z0-9]{12}[0-9]{2}$')), name='reg_establishment_cnpj_14c'),
        ),
        migrations.AddConstraint(
            model_name='partnersnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('partner_cnpj_basic__isnull', True), ('partner_cnpj_basic', ''), ('partner_cnpj_basic__regex', '^[A-Z0-9]{8}$'), _connector='OR'), name='reg_partner_snapshot_cnpj_8c'),
        ),
    ]
