# Generated by Django 5.2.17 on 2026-08-24 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watchers', to='registry.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empresa monitorada',
                'verbose_name_plural': 'empresas monitoradas',
                'db_table': 'portal_watchlist',
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='portal_watchlist_uniq')],
            },
        ),
    ]
