# Generated by Django 5.2.17 on 2026-08-24 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('pipeline', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('entity_type', models.CharField(choices=[('COMPANY', 'Empresa'), ('ESTABLISHMENT', 'Estabelecimento'), ('PARTICIPATION', 'Participação societária')], max_length=24)),
                ('dimension', models.CharField(max_length=40)),
                ('event_type', models.CharField(max_length=60)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('source_effective_date', models.DateField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='registry.company')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='registry.establishment')),
                ('from_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_change_events', to='pipeline.competencerevision')),
                ('historical_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='pipeline.historicalwindow')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='pipeline.importbatch')),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='registry.partnerparticipation')),
                ('to_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_change_events', to='pipeline.competencerevision')),
            ],
            options={
                'verbose_name': 'evento de mudança',
                'verbose_name_plural': 'eventos de mudança',
                'db_table': 'changes_change_event',
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['to_revision', 'event_type'], name='chg_event_to_type'), models.Index(fields=['from_revision'], name='chg_event_from_revision'), models.Index(fields=['company'], name='chg_event_company'), models.Index(fields=['establishment'], name='chg_event_establishment'), models.Index(fields=['participation'], name='chg_event_participation')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_key__regex', '^[0-9a-f]{64}$')), name='chg_event_key_sha256'), models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', False), ('establishment__isnull', True), ('participation__isnull', True)), models.Q(('company__isnull', True), ('establishment__isnull', False), ('participation__isnull', True)), models.Q(('company__isnull', True), ('establishment__isnull', True), ('participation__isnull', False)), _connector='OR'), name='chg_event_exactly_one_target'), models.CheckConstraint(condition=models.Q(('from_revision', models.F('to_revision')), _negated=True), name='chg_event_distinct_revisions')],
            },
        ),
        migrations.CreateModel(
            name='RegionalMonthlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64, unique=True)),
                ('metric_type', models.CharField(max_length=60)),
                ('entity_type', models.CharField(choices=[('COMPANY', 'Empresa'), ('ESTABLISHMENT', 'Estabelecimento')], max_length=24)),
                ('cnae_code', models.CharField(blank=True, max_length=7, null=True)),
                ('registration_status_code', models.CharField(blank=True, max_length=2, null=True)),
                ('company_size_code', models.CharField(blank=True, max_length=2, null=True)),
                ('extra_dimensions', models.JSONField(default=dict)),
                ('value', models.BigIntegerField()),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regional_metrics', to='geography.municipality')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_metrics', to='pipeline.competencerevision')),
            ],
            options={
                'verbose_name': 'métrica regional mensal',
                'verbose_name_plural': 'métricas regionais mensais',
                'db_table': 'changes_regional_monthly_metric',
                'indexes': [models.Index(fields=['revision', 'metric_type'], name='chg_metric_revision_type')],
                'constraints': [models.CheckConstraint(condition=models.Q(('metric_key__regex', '^[0-9a-f]{64}$')), name='chg_metric_key_sha256'), models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='chg_metric_nonnegative')],
            },
        ),
    ]
