# Generated by Django 5.2.17 on 2026-08-24 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveSmallIntegerField()),
                ('scope_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'recorte geográfico',
                'verbose_name_plural': 'recortes geográficos',
                'db_table': 'geography_geographic_scope',
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='geo_scope_code_version_uniq'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='geo_scope_version_gt_0'), models.CheckConstraint(condition=models.Q(('scope_hash__regex', '^[0-9a-f]{64}$')), name='geo_scope_hash_sha256')],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_code', models.CharField(max_length=7, unique=True)),
                ('tom_code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'município',
                'verbose_name_plural': 'municípios',
                'db_table': 'geography_municipality',
                'ordering': ('uf', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('ibge_code__regex', '^[0-9]{7}$')), name='geo_municipality_ibge_7d'), models.CheckConstraint(condition=models.Q(('tom_code__regex', '^[0-9]{4}$')), name='geo_municipality_tom_4d'), models.CheckConstraint(condition=models.Q(('uf__regex', '^[A-Z]{2}$')), name='geo_municipality_uf_2letters')],
            },
        ),
        migrations.CreateModel(
            name='ScopeMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_memberships', to='geography.municipality')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_municipalities', to='geography.geographicscope')),
            ],
            options={
                'verbose_name': 'município do recorte',
                'verbose_name_plural': 'municípios do recorte',
                'db_table': 'geography_scope_municipality',
                'constraints': [models.UniqueConstraint(fields=('scope', 'municipality'), name='geo_scope_municipality_uniq')],
            },
        ),
    ]
