# Generated by Django 5.2.17 on 2026-08-24 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveSmallIntegerField()),
                ('package_hash', models.CharField(max_length=64)),
                ('contract_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('STAGING', 'Em staging'), ('PUBLISHED', 'Publicada'), ('PUBLISHED_WITH_WARNINGS', 'Publicada com alertas'), ('SUPERSEDED', 'Substituída'), ('FAILED_QUALITY_GATE', 'Reprovada na qualidade'), ('FAILED', 'Falhou')], default='STAGING', max_length=32)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('row_counts', models.JSONField(default=dict)),
                ('manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'revisão de competência',
                'verbose_name_plural': 'revisões de competência',
                'db_table': 'pipeline_competence_revision',
                'ordering': ('window_competence', 'revision_number'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('start_competence', models.DateField()),
                ('end_competence', models.DateField()),
                ('contract_version', models.CharField(max_length=20)),
                ('cohort_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('manifest_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PREPARING', 'Em preparação'), ('VALIDATED', 'Validada'), ('ACTIVE', 'Ativa'), ('SUPERSEDED', 'Substituída'), ('FAILED', 'Falhou')], default='DRAFT', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('geographic_scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_windows', to='geography.geographicscope')),
            ],
            options={
                'verbose_name': 'janela histórica',
                'verbose_name_plural': 'janelas históricas',
                'db_table': 'pipeline_historical_window',
                'ordering': ('-start_competence',),
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('PREPARE', 'Preparação'), ('IMPORT', 'Importação'), ('RECALCULATE', 'Recálculo'), ('CLEANUP', 'Limpeza')], max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('VALIDATING', 'Validando'), ('LOADING', 'Carregando'), ('PUBLISHING', 'Publicando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='RECEIVED', max_length=24)),
                ('phase', models.CharField(blank=True, max_length=50, null=True)),
                ('counters', models.JSONField(default=dict)),
                ('sanitized_options', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('competence_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='pipeline.competencerevision')),
            ],
            options={
                'verbose_name': 'lote de processamento',
                'verbose_name_plural': 'lotes de processamento',
                'db_table': 'pipeline_import_batch',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('FATAL', 'Fatal'), ('WARNING', 'Alerta')], max_length=16)),
                ('entity_type', models.CharField(blank=True, max_length=24, null=True)),
                ('entity_key', models.CharField(blank=True, max_length=80, null=True)),
                ('eligible_rows', models.BigIntegerField()),
                ('affected_rows', models.BigIntegerField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competence_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_issues', to='pipeline.competencerevision')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_issues', to='pipeline.importbatch')),
            ],
            options={
                'verbose_name': 'ocorrência de qualidade',
                'verbose_name_plural': 'ocorrências de qualidade',
                'db_table': 'pipeline_data_quality_issue',
            },
        ),
        migrations.CreateModel(
            name='PackageArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('MANIFEST', 'Manifesto'), ('COMPANIES', 'Empresas'), ('ESTABLISHMENTS', 'Estabelecimentos'), ('PARTNERS', 'Sócios')], max_length=20)),
                ('relative_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('row_count', models.PositiveBigIntegerField()),
                ('schema', models.JSONField(default=dict)),
                ('competence_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_artifacts', to='pipeline.competencerevision')),
            ],
            options={
                'verbose_name': 'artefato de pacote',
                'verbose_name_plural': 'artefatos de pacote',
                'db_table': 'pipeline_package_artifact',
            },
        ),
        migrations.CreateModel(
            name='SourceArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=40)),
                ('source_url', models.URLField(max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('competence', models.DateField()),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('acquired_at', models.DateTimeField()),
                ('competence_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_artifacts', to='pipeline.competencerevision')),
            ],
            options={
                'verbose_name': 'artefato-fonte',
                'verbose_name_plural': 'artefatos-fonte',
                'db_table': 'pipeline_source_artifact',
            },
        ),
        migrations.CreateModel(
            name='WindowCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.DateField()),
                ('position', models.PositiveSmallIntegerField()),
                ('historical_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competences', to='pipeline.historicalwindow')),
            ],
            options={
                'verbose_name': 'competência da janela',
                'verbose_name_plural': 'competências da janela',
                'db_table': 'pipeline_window_competence',
                'ordering': ('historical_window', 'position'),
            },
        ),
        migrations.AddField(
            model_name='competencerevision',
            name='window_competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='pipeline.windowcompetence'),
        ),
        migrations.AddConstraint(
            model_name='historicalwindow',
            constraint=models.CheckConstraint(condition=models.Q(('start_competence__lte', models.F('end_competence'))), name='pipe_window_start_lte_end'),
        ),
        migrations.AddConstraint(
            model_name='historicalwindow',
            constraint=models.UniqueConstraint(models.Value(1), condition=models.Q(('status', 'ACTIVE')), name='pipe_one_active_window'),
        ),
        migrations.AddConstraint(
            model_name='historicalwindow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('VALIDATED', 'ACTIVE', 'SUPERSEDED')), _negated=True), models.Q(('cohort_hash__regex', '^[0-9a-f]{64}$'), ('manifest_hash__regex', '^[0-9a-f]{64}$')), _connector='OR'), name='pipe_window_published_hashes'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status', 'started_at'], name='pipe_batch_status_started'),
        ),
        migrations.AddIndex(
            model_name='dataqualityissue',
            index=models.Index(fields=['import_batch', 'severity', 'rule_code'], name='pipe_dqi_batch_severity_rule'),
        ),
        migrations.AddConstraint(
            model_name='dataqualityissue',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_rows__gte', 0)), name='pipe_dqi_eligible_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dataqualityissue',
            constraint=models.CheckConstraint(condition=models.Q(('affected_rows__gte', 0)), name='pipe_dqi_affected_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dataqualityissue',
            constraint=models.CheckConstraint(condition=models.Q(('affected_rows__lte', models.F('eligible_rows'))), name='pipe_dqi_affected_lte_eligible'),
        ),
        migrations.AddConstraint(
            model_name='packageartifact',
            constraint=models.UniqueConstraint(fields=('competence_revision', 'artifact_type'), name='pipe_package_artifact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='packageartifact',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='pipe_package_hash_sha256'),
        ),
        migrations.AddConstraint(
            model_name='sourceartifact',
            constraint=models.UniqueConstraint(fields=('competence_revision', 'source_type', 'file_name'), name='pipe_source_artifact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sourceartifact',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='pipe_source_hash_sha256'),
        ),
        migrations.AddConstraint(
            model_name='windowcompetence',
            constraint=models.UniqueConstraint(fields=('historical_window', 'competence'), name='pipe_window_competence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='windowcompetence',
            constraint=models.UniqueConstraint(fields=('historical_window', 'position'), name='pipe_window_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='competencerevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gt', 0)), name='pipe_revision_number_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='competencerevision',
            constraint=models.CheckConstraint(condition=models.Q(('package_hash__regex', '^[0-9a-f]{64}$')), name='pipe_revision_hash_sha256'),
        ),
        migrations.AddConstraint(
            model_name='competencerevision',
            constraint=models.UniqueConstraint(fields=('window_competence', 'revision_number'), name='pipe_revision_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='competencerevision',
            constraint=models.UniqueConstraint(fields=('window_competence', 'package_hash'), name='pipe_revision_package_uniq'),
        ),
        migrations.AddConstraint(
            model_name='competencerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PUBLISHED', 'PUBLISHED_WITH_WARNINGS'))), fields=('window_competence',), name='pipe_one_active_revision'),
        ),
    ]
