# Generated by Django 5.2.17 on 2026-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historicalwindow',
            name='pipe_window_published_hashes',
        ),
        migrations.AddConstraint(
            model_name='historicalwindow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('VALIDATED', 'ACTIVE', 'SUPERSEDED')), _negated=True), models.Q(('cohort_hash__isnull', False), ('manifest_hash__isnull', False), ('cohort_hash__regex', '^[0-9a-f]{64}$'), ('manifest_hash__regex', '^[0-9a-f]{64}$')), _connector='OR'), name='pipe_window_published_hashes'),
        ),
    ]
